name: Lock closed inactive issues

on:
  schedule:
    # Run at 16:00 every day
    - cron: '0 16 * * *'

jobs:
  lock_closed:
    if: github.repository == 'angular/angular'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@dbba62b87b3430bb642726f82c5d29f8fcbaf33f
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
